/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/architecture': RouteRecordInfo<'/architecture', '/architecture', Record<never, never>, Record<never, never>>,
    '/book_blog': RouteRecordInfo<'/book_blog', '/book_blog', Record<never, never>, Record<never, never>>,
    '/food_blog': RouteRecordInfo<'/food_blog', '/food_blog', Record<never, never>, Record<never, never>>,
    '/magazines/magazine1': RouteRecordInfo<'/magazines/magazine1', '/magazines/magazine1', Record<never, never>, Record<never, never>>,
    '/magazines/magazine10': RouteRecordInfo<'/magazines/magazine10', '/magazines/magazine10', Record<never, never>, Record<never, never>>,
    '/magazines/magazine2': RouteRecordInfo<'/magazines/magazine2', '/magazines/magazine2', Record<never, never>, Record<never, never>>,
    '/magazines/magazine3': RouteRecordInfo<'/magazines/magazine3', '/magazines/magazine3', Record<never, never>, Record<never, never>>,
    '/magazines/magazine4': RouteRecordInfo<'/magazines/magazine4', '/magazines/magazine4', Record<never, never>, Record<never, never>>,
    '/magazines/magazine5': RouteRecordInfo<'/magazines/magazine5', '/magazines/magazine5', Record<never, never>, Record<never, never>>,
    '/magazines/magazine6': RouteRecordInfo<'/magazines/magazine6', '/magazines/magazine6', Record<never, never>, Record<never, never>>,
    '/magazines/magazine7': RouteRecordInfo<'/magazines/magazine7', '/magazines/magazine7', Record<never, never>, Record<never, never>>,
    '/magazines/magazine8': RouteRecordInfo<'/magazines/magazine8', '/magazines/magazine8', Record<never, never>, Record<never, never>>,
    '/magazines/magazine9': RouteRecordInfo<'/magazines/magazine9', '/magazines/magazine9', Record<never, never>, Record<never, never>>,
    '/movie_blog': RouteRecordInfo<'/movie_blog', '/movie_blog', Record<never, never>, Record<never, never>>,
    '/music_blog': RouteRecordInfo<'/music_blog', '/music_blog', Record<never, never>, Record<never, never>>,
  }
}
